on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        env:
          BRANCH: $(echo ${{ github.ref_name }} | awk '{ print toupper($0) }')
        run: |
          echo "Branch: $BRANCH"
          SECRET=${{ secrets[format('{0}_A', env.BRANCH)] }}
          echo $SECRET

