on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        run: |
          BRANCH=$(echo ${{ github.ref_name }} | awk '{ print toupper($0) }')
          echo $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo ${{ env.BRANCH }}
          SECRET=${{ secrets[format('{0}_A', env.BRANCH)] }}
          echo $SECRET

