name: Test Actions

on:
  push :
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        if: github.ref_name == 'main'
        run: |
          echo "Works"