name: Test Actions

on:
  push :
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Evaluating expressions
        run: |
          echo "The branch is ${{ github.ref_name }} & \
          event is ${{ github.event_name }}"

  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Evaluating secret
        run: |
          echo "The secret is ${{ secrets['TEST'] }}"