name: Deploy Maintenance Page

on:
  workflow_dispatch:
    inputs:
      maintenance_mode:
        description: 'Enable maintenance mode'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
      environment:
        description: 'Comma-separated list of environments'
        required: true

env:
  REACT_APP_SITE_MAINTENANCE_MODE: ${{ github.event.inputs.maintenance_mode }}

permissions:
  id-token: write
  contents: read
  pull-requests: read
  repository-projects: read
  issues: read

jobs:
  setup_environment:
    name: Setup Matrix
    runs-on: ubuntu-22.04
    steps:
      - name: Setup matrix
        id: setup_matrix
        run: |
          echo "test=$(jq -cn --argjson environments ${{ github.event.inputs.environment }} '{environment: $environments}')" >> $GITHUB_OUTPUT
    outputs:
      test: ${{ steps.setup_matrix.outputs.test }}

  maintenance_mode:
    needs: setup_environment
    strategy:
      matrix: ${{ fromJson(needs.setup_environment.outputs.test) }}

    name: Maintenance Mode for ${{ matrix.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: |
          echo "Maintenance: $REACT_APP_SITE_MAINTENANCE_MODE"
          echo "Environment: ${{ matrix.environment }}"
